### ISSUE TITLE
Error in docking ara-web with ara API interface

### ISSUE THREAD

**Issue by tzkyard** [ansible-community/ara-web#16]
## My os  
CentOS Linux release 7.6.1810 (Core)      3.10.0-957.el7.x86_64

## version of npm
[root@server-ara public]# npm --version
5.6.0
## Some configure file   
```  
ara-web/public/config.json  
{
  "apiURL": "http://192.168.6.141:8000"
}   
```
## The status of ara api and ara-web
![image](https://user-images.githubusercontent.com/49138808/63148852-07501800-c035-11e9-854b-79d7714c5af7.png)  
![image](https://user-images.githubusercontent.com/49138808/63148871-0f0fbc80-c035-11e9-85af-5ec37dea9ce0.png)

## My problem
The ara-web shows an error:
![image](https://user-images.githubusercontent.com/49138808/63148906-29499a80-c035-11e9-9324-523c68afa222.png)

So how to deal with this problem?

**Comment by dmsimard** [comment]
@tzkyard Hi and thanks for the report !

Does it work if you add 192.168.6.141 in the [ARA_CORS_ORIGIN_WHITELIST](https://ara.readthedocs.io/en/latest/api-configuration.html#ara-cors-origin-whitelist) setting for the API server ?

Do you see an error in your browser's javascript console ?

**Comment by dmsimard** [comment]
Hi @tzkyard. Have you been able to make it work with ``ARA_CORS_ORIGIN_WHITELIST`` ?

Would like to know so we can take the appropriate action for this issue.

**Comment by rndmh3ro** [comment]
I'm having the same problem.
Here's my ara-api settings.

`CORS_ORIGIN_ALLOW_ALL` doesn't seem to have an effect.

`CORS_ORIGIN_WHITELIST` is set to all IP-addresses and domain names, this ec2-instance has.

```
  CORS_ORIGIN_ALLOW_ALL: true
  CORS_ORIGIN_REGEX_WHITELIST: !!python/object:box.BoxList
    box_class: *id001
    box_options: {}
    box_org_ref: 0
  CORS_ORIGIN_WHITELIST: !!python/object/new:box.BoxList
    listitems:
    - http://127.0.0.1:8000
    - http://127.0.0.1:3000
    - http://localhost:3000
    - http://localhost:8000
    - http://ec2-3-122-159-152.eu-central-1.compute.amazonaws.com:3000
    - http://ec2-3-122-159-152.eu-central-1.compute.amazonaws.com:8000
    - http://ec2-3-122-159-152.eu-central-1.compute.amazonaws.com
    - http://3.122.159.152:3000
    - http://3.122.159.152:8000
    - http://3.122.159.152
    - http://172.31.4.185:3000
    - http://172.31.4.185:8000
    - http://172.31.4.185
```

I even tried to remove the cors-code from the ara-api but nothing seems to help.
